### ISSUE TITLE
xmcsSet - zip - space in folder name

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/xcms#65]
And example:
- Data FOO
  - QC
    - QC1.mzXML
    - QC2.mzXML
  - BAR
    - BAR1.mzXML
    - BAR2.mzXML

```
find: `FOO': No such file or directory
find: `2': No such file or directory
find: `/work/project/w4m/galaxy4metabolomics/galaxy-dist/database/jobs_directory/000/131/131287/working/FOO': No such file or directory
find: `2': No such file or directory
Warning message:
running command 'find $PWD/FOO 2 -not -name '\.*' -not -path '*conda-env*' -type f -name "*"' had status 1 
Error in checkForRemoteErrors(val) : 
  46 nodes produced errors; first error: invalid UTF-8 input in readChar()
Calls: do.call ... xcmsSet -> xcmsClusterApply -> checkForRemoteErrors
Execution halted
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/work/project/w4m/galaxy4metabolomics/galaxy-dist/database/jobs_directory/000/131/131287/set_metadata_y5adti.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/work/project/w4m/galaxy4metabolomics/galaxy-dist/lib/galaxy_ext/metadata/set_metadata.py", line 14, in <module>
    import cPickle
ImportError: No module named cPickle
```

**Comment by lecorguille** [comment]
Should be fix with https://github.com/workflow4metabolomics/xcms/pull/84/commits/ba550315acbfaadbb4e05c9e6ec4f7281e5924cf in the xcms3 wrappers
